version: "3"
services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wiki
      MYSQL_USER: wikijs
      MYSQL_ROOT_PASSWORD: wikijsrocks
      MYSQL_PASSWORD: wikijsrocks
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - mysql-db-data:/var/lib/mysql

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "3000:3000"

  wikijs-sitemap:
    image: hostwiki/wikijs-sitemap:latest
    depends_on:
      - db
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "3012:3012"

volumes:
  mysql-db-data: